### ISSUE TITLE
creative chat modem crashes server on chat_message event

### ISSUE THREAD

**Issue by Merith-TK** [hugeblank/allium-peripherals#11]
https://mclo.gs/IGtLhrI < clien

https://mclo.gs/qTixVVu < server

I set an creative chat modem to capture `"."`, and said something in chat

**Comment by piprett** [comment]
![image](https://user-images.githubusercontent.com/49862976/183305306-fc9b76f1-ffaf-49e9-a487-816c78c7b24c.png)
This is the error screen i get on the client

**Comment by hugeblank** [comment]
ahhhh yep. I know exactly what's going on and I apologize for not considering it when testing before release. I'll have a patch out within the next 24 hours.

This has also inspired me to create a test suite in my dev world, lmao
