### ISSUE TITLE
Entangled Modem recipe actually crafts a Chat Modem

### ISSUE THREAD

**Issue by object-Object** [hugeblank/allium-peripherals#14]
On version v0.4.0-rc.1.

**Comment by hugeblank** [comment]
lmao. Thanks for pointing it out. 

If you want you can create a datapack to fix it until I get around to making another release. Download [this json](https://github.com/hugeblank/allium-peripherals/blob/dev/src/main/resources/data/allium_peripherals/recipes/entangled_modem.json), replace the result item with "allium_peripherals:entangled_modem".
