### ISSUE TITLE
Setting a chat capture with an invalid pattern causes you to crash / be kicked from the world when you send a chat message

### ISSUE THREAD

**Issue by object-Object** [hugeblank/allium-peripherals#15]
Repro steps:
* Put a chat modem on a computer
* Run `lua`, then call `peripheral.call("right", "capture", "[")` (replace `right` with the side you put it on)
* Send any chat message

Version: v0.4.0-rc.1

**Comment by hugeblank** [comment]
ooh nice! thanks for catching this.

**Comment by hugeblank** [comment]
Latest [release candidate](https://github.com/hugeblank/allium-peripherals/releases/tag/v0.4.0-rc.2%2Bmc1.18.2) fixes this
