### ISSUE TITLE
Update to CC:R 1.95.3 on MC 1.16.5

### ISSUE THREAD

**Issue by Merith-TK** [hugeblank/allium-peripherals#2]
I help maintain a fork of a fork of a fork of a fork of CC:T, 

My fork aims to keep parity with CC:T, while only adding fabric specific bugfixes as nessecary. 

I was hoping you could update your mod to 1.16.5 so that I may reccomend this in my readme for a mod that can be used with this one, as it adds features akin to plethora

**Comment by hugeblank** [comment]
I've been meaning to for some time now, conveniently my classes have just ended for the semester and I'm now on break! I'll work on getting this ported over to CC:R, I've been meaning to do so since I heard of it. 

If I were to depend on Zundrels fork, would it work with your fork too?

**Comment by Merith-TK** [comment]
> If I were to depend on Zundrels fork, would it work with your fork too? 

I have no clue to that would be big ***maybe***?
 My fork is the most up to date and will be "relatively constantly updated" along side CC:T,

https://github.com/Toad-Dev/cc-peripheral-test

this is an example of a peripheral for CC:R, so if you use this example for the 1.16.5 version it should work just fine,

**Comment by Merith-TK** [comment]
I would say, go ahead and make a peripheral based off zundrel's fork and then we can test if it works, toad-dev made a peripheral for an older version of CC:R (zundrels version before i stepped in) so in theory it should work? the peripheral API hasnt been changed at all IIRC

**Comment by hugeblank** [comment]
Working on this now - I'll just depend on your mod, feels easier lol

**Comment by Merith-TK** [comment]
Yeah its only called CC:RU because CC:R is still taken by Zundrel, (otherwise its save to refer to it as CC:R lol
