### ISSUE TITLE
curseforge release?

### ISSUE THREAD

**Issue by Merith-TK** [hugeblank/allium-peripherals#4]
Please? One of the players on my SMP is making a curseforge modpack...

**Comment by hugeblank** [comment]
readme

**Comment by hugeblank** [comment]
ope just saw the other issue reported

**Comment by hugeblank** [comment]
as it turns out the readme has a bad link. See here:
https://www.curseforge.com/minecraft/mc-mods/allium-peripherals

I've also fixed this in the readme. clicking the curseforge images in the title will direct you to the CF link.
