### ISSUE TITLE
Chat modem doesn't drop when broken

### ISSUE THREAD

**Issue by object-Object** [hugeblank/allium-peripherals#8]
This could totally be user error, but I've broken several chat modems with various tools and never had the item drop. Playing v0.2.2+1.18.2.

**Comment by hugeblank** [comment]
it's definitely not user error. The PR'd update from 1.16 to 1.18 didn't add loot table jsons which weren't necessary back then. Thanks for bringing this to my attention, I'll add them when I have some time. In the mean time you could create a datapack and manually create the loot tables.
